# Generated by Django 5.2 on 2025-09-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('localistion', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('en_attente', 'En ttente'), ('en_cours', 'En cours'), ('resolu', 'Resolu')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
