# Generated by Django 5.2.5 on 2025-10-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_fuite_delete_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuite',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='fuite',
            name='longitude',
        ),
        migrations.AddField(
            model_name='fuite',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fuite',
            name='comname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fuite',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='fuite',
            name='status',
            field=models.CharField(default='NOK', max_length=50),
        ),
    ]
