# Generated by Django 5.2.5 on 2025-10-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_fuite_latitude_remove_fuite_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuite',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
