# Generated by Django 5.2.5 on 2025-10-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_rename_comname_fuite_complaint_name_fuite_commune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuite',
            name='quartier',
            field=models.CharField(null=True),
        ),
    ]
