# Generated by Django 5.2.5 on 2025-10-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_fuite_quartier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuite',
            name='quartier',
            field=models.CharField(choices=[('Bandalungwa', 'Bandalungwa'), ('Barumbu', 'Barumbu'), ('Bumbu', 'Bumbu'), ('Gombe', 'Gombe'), ('Kalamu', 'Kalamu'), ('Kasa-Vubu', 'Kasa-Vubu'), ('Kimbanseke', 'Kimbanseke'), ('Kinshasa', 'Kinshasa'), ('Kintambo', 'Kintambo'), ('Kisenso', 'Kisenso'), ('Lemba', 'Lemba'), ('Limete', 'Limete'), ('Lingwala', 'Lingwala'), ('Makala', 'Makala'), ('Maluku', 'Maluku'), ('Masina', 'Masina'), ('Matete', 'Matete'), ('Mont Ngafula', 'Mont Ngafula'), ('Ndjili', 'Ndjili'), ('Ngaba', 'Ngaba'), ('Ngaliema', 'Ngaliema'), ('Ngiri-Ngiri', 'Ngiri-Ngiri'), ('Nsele', 'Nsele'), ('Selembao', 'Selembao')], null=True),
        ),
    ]
