# Generated by Django 5.2.5 on 2025-10-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_fuite_quartier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuite',
            name='quartier',
            field=models.CharField(null=True),
        ),
    ]
