# Generated by Django 5.2.5 on 2025-10-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_fuite_quartier'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuite',
            name='opt',
            field=models.CharField(blank=True, null=True),
        ),
    ]
