# Generated by Django 5.2.5 on 2025-10-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_fuite_opt'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuite',
            name='verified_opt',
            field=models.BooleanField(default=False),
        ),
    ]
