# Generated by Django 5.2.5 on 2025-10-19 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_fuite_verified_opt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='NOT RESOLVED')),
                ('remember_count', models.IntegerField(default=0)),
                ('fuite', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='reports.fuite')),
            ],
        ),
    ]
