# Generated by Django 5.2.5 on 2025-10-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='resolver_email',
            field=models.EmailField(default='kabudon19@gmail.com', max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='resolver_phone',
            field=models.CharField(default='+243892649177', max_length=12, verbose_name='phone'),
            preserve_default=False,
        ),
    ]
