# Generated by Django 5.2.5 on 2025-10-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_mission_resolver_email_mission_resolver_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuite',
            name='email',
            field=models.EmailField(blank=True, help_text='Email du signaleur pour les notifications', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='resolver_email',
            field=models.EmailField(default='kabudon19@gmail.com', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='resolver_phone',
            field=models.CharField(default='+243892649177', max_length=12, verbose_name='phone'),
        ),
    ]
