# Generated by Django 5.2.8 on 2025-11-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_fuite_email_alter_mission_resolver_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('commune', models.CharField(choices=[('Bandalungwa', 'Bandalungwa'), ('Barumbu', 'Barumbu'), ('Bumbu', 'Bumbu'), ('Gombe', 'Gombe'), ('Kalamu', 'Kalamu'), ('Kasa-Vubu', 'Kasa-Vubu'), ('Kimbanseke', 'Kimbanseke'), ('Kinshasa', 'Kinshasa'), ('Kintambo', 'Kintambo'), ('Kisenso', 'Kisenso'), ('Lemba', 'Lemba'), ('Limete', 'Limete'), ('Lingwala', 'Lingwala'), ('Makala', 'Makala'), ('Maluku', 'Maluku'), ('Masina', 'Masina'), ('Matete', 'Matete'), ('Mont Ngafula', 'Mont Ngafula'), ('Ndjili', 'Ndjili'), ('Ngaba', 'Ngaba'), ('Ngaliema', 'Ngaliema'), ('Ngiri-Ngiri', 'Ngiri-Ngiri'), ('Nsele', 'Nsele'), ('Selembao', 'Selembao')], max_length=100)),
                ('quartiers_responsable', models.JSONField(default=list, help_text="Liste des quartiers dont l'agent est responsable")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
    ]
