# Generated by Django 5.2.8 on 2025-11-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_agentprofile_mission_mission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
