# Generated by Django 5.2.8 on 2025-11-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_alter_agentprofile_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentprofile',
            options={'ordering': ['commune', 'role', 'email'], 'verbose_name': 'Profil Agent', 'verbose_name_plural': 'Profils Agents'},
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='role',
            field=models.CharField(choices=[('quartier', 'Responsable de Quartier'), ('commune', 'Responsable de Commune'), ('admin', 'Administrateur')], default='quartier', help_text='Rôle et niveau de permissions', max_length=20),
        ),
    ]
